# -*- coding: utf-8 -*-
"""k-means

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iA7aLOxVDOikNQPkkxfcle2DLafn9Fyt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

url = "https://raw.githubusercontent.com/Gilan08/k-means/main/Mall_Customers.csv"
data = pd.read_csv(url)

X = data[['Annual Income (k$)', 'Spending Score (1-100)']]

inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia, marker='o')
plt.xlabel('Jumlah Cluster')
plt.ylabel('Inertia')
plt.title('Metode Elbow')
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)
data['Cluster'] = kmeans.fit_predict(X)

plt.figure(figsize=(10,6))
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)',
                hue='Cluster', palette='Set1', data=data, s=100)
plt.title('Customer Segmentation (K-Means)')
plt.show()